### ISSUE TITLE
Search on cocoapods.org doesn't work anymore 

### ISSUE THREAD

**Issue by xlbs-rm** [CocoaPods/cocoapods.org#351] opened 2018-03-12 21:21 UTC
Cannot search for Pods? Are there alternatives?
Google search with site:cocoapods.org is not really a alternative.

Tested on 2 different Devices, Browsers: Chrome, FF

Expected: List of Results e.g. for: Realm (automatic written in Uppercase REALM)
Given: Result shows no result, URL has right search Param, pods are available example: https://cocoapods.org/pods/Realm

...seems to be the same Problem like: CocoaPods/cocoapods.org#350

**Comment by orta** [comment] 2018-03-13 13:00
Yeah, looks like a dupe of #350 - closing

**Comment by xlbs-rm** [comment] 2018-03-13 13:02
Search is working again (right now)

**Comment by orta** [comment] 2018-03-13 13:02
It's not a dupe. But it just looks like intermittent API issues.

You can always  use the CLI: `pod search orta`

**Comment by benasher44** [comment] 2018-03-23 21:48
I'm getting this as well in Safari; I'm see Access-Control-Allow-Origin errors:

<img width="1676" alt="screen shot 2018-03-23 at 2 48 17 pm" src="https://user-images.githubusercontent.com/1120429/37854719-4ee3e094-2ea9-11e8-92f4-ba5015280b38.png">

**Comment by benasher44** [comment] 2018-03-26 16:37
I figured out why this happens in Safari 11. I'll file a new ticket.

**Comment by benasher44** [comment] 2018-03-26 16:45
Whoops! Didn't mean to close and reopen then 🤦‍♂️

**Comment by dtrenz** [comment] 2018-03-26 17:15
Search isn't working for me in Chrome.

It appears that the AWS search request is timing out at the host: https://aws-search.cocoapods.org/api/v1/pods.picky.hash.json?query=Firebase&ids=20&offset=0&sort=quality

![image](https://user-images.githubusercontent.com/639833/37921385-b35473e0-30f7-11e8-86ad-0fecff5fdbd5.png)

**Closed** 2018-04-13 10:32 UTC

**Comment by joeboyscout04** [comment] 2018-04-20 09:18
I'm still getting this issue in Chrome...is there a fix for this? 

<img width="1670" alt="screen shot 2018-04-20 at 11 15 42" src="https://user-images.githubusercontent.com/1489809/39042981-8e22422a-448c-11e8-9d59-ff6013ad9082.png">

**Comment by naamtechkon** [comment] 2018-04-23 04:32
I get the same problem - I put in any text and no results! Are cocoapods no longer sanctioned by apple? Or has the site been abandoned?

**Comment by segiddins** [comment] 2018-04-23 04:35
There's an ongoing incident, you can follow status.cocoapods.org to stay up-to-date

**Comment by ntkon** [comment] 2018-04-23 04:58
Thanks for that - nice to get a quick reply.

**Comment by dilizarov** [comment] 2018-05-04 07:37
It's not working again. It seems to work less often than it is broken.

**Comment by segiddins** [comment] 2018-05-04 15:01
Again, please follow the CocoaPods status page for updates. Griping in an issue won’t get anyone time to fix it any faster.

**Comment by dtrenz** [comment] 2018-05-04 17:52
In the meantime, maybe Google can dull the pain a tiny bit? – https://www.google.com/search?q=site%3Acocoapods.org+alamofire

<img width="603" alt="image" src="https://user-images.githubusercontent.com/639833/39643293-53d734ba-4fa2-11e8-9fed-20b04f782314.png">
