### ISSUE TITLE
Headings are incorrectly coloured on the pod detail page

### ISSUE THREAD

**Issue by kylef** [CocoaPods/cocoapods.org#137] opened 2015-04-08 18:56 UTC
Example: https://cocoapods.org/pods/JSONWebToken
Colours:
- H1 - Black
- H2 - Black
- H3 - Dark red
- H4 - Black

H1 and H2 should be brighter reds as per the design.

**Comment by orta** [comment] 2015-09-26 09:37
Closing as by design, I want the red headers to be owned by CP ( like the title/side )

**Closed by orta** 2015-09-26 09:37 UTC
